dist: xenial

language: php

php: "7.4"

jobs:
  include:

    - stage: test
      name: Default Test
      after_script:
        - test -f ./tests/reports/clover.xml && composer test-report || true

    - name: Test with PHP 5.6
      env:
        WORDPRESS_IMAGE_VERSION: php5.6

    - name: Test with PHP 7.2
      env:
        WORDPRESS_IMAGE_VERSION: php7.2

    - stage: deploy
      name: Tag Release
      if: tag IS present
      before_deploy:
        - npm run release
      deploy:
        provider: releases
        api_key:
          secure: HheYiv6c8ipHzMZBTH7xcKrOwCllvJTtfiTffAPK6XubWe3Kudn6IJUv0p1gmRhWXxZ5ciJQ/sgiCRGTRm/bubHs4tS7JOmpmoTdkrXajTxyyDCKpxhtT43nie0vNF+pWqVu2yOjhDR4pwtWjpQdzEKOz0kn0XSMT+vGsKQD50w=
        overwrite: true
        skip_cleanup: true
        file:
          - stream.zip
          - stream-$TRAVIS_TAG.zip

services:
  - docker

before_install:
  - docker-compose pull wordpress
  - nvm install
  - nvm use

install:
  - npm install

script:
  - npm run lint
  - npm run phpunit
  - npm run phpunit-multisite

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
