dist: xenial

language:
  - php
  - node_js

php:
  - "7.3"

services:
  - "docker"

install:
  - npm install

before_script:
  - docker-compose up -d
  - sleep 10

script:
  - npm run cli -- printenv
  - npm run lint
  - npm run phpunit

after_script:
  - npm run phpunit-report

before_deploy:
  - npm run build

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file: build/**/*
  on:
    tags: true

# Pull requests are built by default.
branches:
  only:
  - master
  - develop

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
