dist: xenial

language: php

php:
  - "5.6"
  - "7.0"
  - "7.2"
  - "7.3"

addons:
  apt:
    packages:
      # For xmllint.
      - libxml2-utils
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

jobs:
  include:
    - name: Release Package
      php: "7.3"
      env: WP_VERSION=latest WP_MULTISITE=0 WP_RELEASE=1

services:
  - mysql

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - export DEV_LIB_ONLY="phpunit"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run lint
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - test -f ./tests/reports/clover.xml && composer test-report || true

before_deploy:
  - npm run release

deploy:
  provider: releases
  api_key:
    secure: HheYiv6c8ipHzMZBTH7xcKrOwCllvJTtfiTffAPK6XubWe3Kudn6IJUv0p1gmRhWXxZ5ciJQ/sgiCRGTRm/bubHs4tS7JOmpmoTdkrXajTxyyDCKpxhtT43nie0vNF+pWqVu2yOjhDR4pwtWjpQdzEKOz0kn0XSMT+vGsKQD50w=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - stream.zip
    - stream-$TRAVIS_TAG.zip
  on:
    tags: true
    condition: "$WP_RELEASE = 1"

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
