version: '3'

services:

  mysql:
    image: mysql:5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    image: xwpco/stream-wordpress:${WORDPRESS_IMAGE_VERSION:-latest}
    build:
      context: ./local/docker/wordpress
      args:
        PHP_VERSION: "${WORDPRESS_IMAGE_VERSION:-latest}"
        XDEBUG_VERSION: "${WORDPRESS_XDEBUG_VERSION:-2.9.6}"
    depends_on:
      - mysql
      - db_phpunit
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000" # Xdebug
    volumes:
      - .:/var/www/html/wp-content/plugins/stream-src # Working directory.
      - ./build:/var/www/html/wp-content/plugins/stream # Built version for testing.
      - ./local/public:/var/www/html # WP core files.
      - ./local/config/.htaccess:/var/www/html/.htaccess
      - ./local/config/wp-cli.yml:/var/www/html/wp-cli.yml
      - ./local/config/wp-config.php:/var/www/html/wp-config.php
      - ./local/config/wp-tests-config.php:/var/www/html/wp-tests-config.php
      - ./local/config/sunrise.php:/var/www/html/wp-content/sunrise.php
    restart: always
    environment:
      COMPOSER_HOME: /tmp/.composer
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.
      WP_TESTS_DIR: /var/www/html/wp-content/plugins/stream-src/vendor/wp-phpunit/wp-phpunit
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/wp-tests-config.php

  db_phpunit:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_test"
      MYSQL_ROOT_PASSWORD: ""

  # Capture and display all email sent by WordPress.
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data: {}
  wp_data: {}
